In [1]:
import pandas as pd
import numpy as np

In [2]:
schedule = pd.read_csv('./schedule.csv', index_col=0)
ct = schedule['producer->compression_type'].to_list()
options = ['None', 'gzip', 'snappy', 'lz4']
for i, item in enumerate(ct):
    ct[i] = options.index(ct[i])
schedule['producer->compression_type'] = ct

In [3]:
states = pd.read_csv('states.csv', index_col=0).sort_values(by=['run_index'])
states = states.loc[:, (states != states.iloc[0]).any()]
states = states[~states.index.duplicated(keep='last')]

In [4]:
schedule

,producer->batch_size,producer->linger_ms,producer->buffer_memory,producer->compression_type,producer->topics,broker->num.network.threads,broker->num.io.threads,broker->queued.max.requests,consumer->fetch_wait_max_ms
index,,,,,,,,,
0,169550,59,8862781,3,9,3,2,159,327
1,194027,18,12456982,1,2,9,5,425,118
2,141063,76,7031483,3,7,16,14,135,226
3,95794,30,25065833,1,1,13,13,281,358
4,212093,99,9119279,2,1,4,15,292,355
...,...,...,...,...,...,...,...,...,...
4995,144458,27,5307122,1,3,4,6,491,405
4996,2126,32,454174,1,3,8,23,413,279
4997,182683,36,23625202,2,10,14,21,422,283
4998,10734,88,30600801,1,7,11,15,71,372
4999,24894,32,6982257,1,9,13,9,30,444

In [5]:
states

,Latency,Throughput,gc_collection_count,gc_collection_time,jvm_loaded_class_count,jvm_total_loaded_class_count,last_gc_info_duration,memory_heap_usage_used,memory_non_heap_usage_used,network_request_FetchConsumer_ResponseSendTimeMs,...,os_process_cpu_load,os_process_cpu_time,os_system_cpu_load,server_broker_topics_AllTopicsBytesIn,server_broker_topics_AllTopicsBytesOut,server_broker_topics_AllTopicsMessagesIn,server_broker_topics_TotalFetchRequestsPerSec,server_broker_topics_TotalProduceRequestsPerSec,server_purgatory_NumDelayedFetchRequests,threading_thread_count
run_index,,,,,,,,,,,,,,,,,,,,,
0,3.01,0.02,6.4,63.6,7007.06,7137.2,15.49,1.925339e+08,71712131.82,50019.0,...,0.02,1.366600e+10,0.59,5695.80,251104.37,16.91,78.19,11.40,24.77,68.61
1,1.78,0.02,5.9,63.9,6995.72,7119.2,18.73,1.885344e+08,71135449.87,64504.0,...,0.02,1.134200e+10,0.50,5685.01,523213.30,17.18,101.70,17.10,26.71,68.32
2,3.28,0.02,6.4,74.2,7014.73,7146.9,22.48,1.912293e+08,71627635.90,53240.0,...,0.02,1.391300e+10,0.60,4749.37,203797.73,16.97,80.22,8.60,27.23,68.64
3,2.92,0.03,6.7,72.9,6994.82,7121.0,24.11,1.893663e+08,71730345.43,51778.5,...,0.02,1.460000e+10,0.62,5453.65,239167.35,16.53,76.61,16.40,25.80,68.73
4,3.58,0.02,6.2,65.3,6982.51,7112.8,18.01,1.946635e+08,71360422.61,49170.0,...,0.02,1.391300e+10,0.61,4636.71,200732.30,16.89,74.14,8.52,26.52,68.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2.45,0.03,6.4,49.1,6992.35,7122.7,9.74,1.993351e+08,71712634.67,53242.5,...,0.02,1.311200e+10,0.56,4754.21,243688.39,14.39,78.87,14.30,25.53,68.64
4996,2.91,0.03,6.3,53.7,7014.80,7146.1,9.76,1.966880e+08,71835396.86,55501.0,...,0.02,1.339100e+10,0.54,4939.66,215679.50,15.21,77.23,14.78,24.85,68.66
4997,2.50,0.57,6.3,57.4,7005.92,7134.1,16.57,2.005105e+08,71638150.88,60341.0,...,0.02,1.343800e+10,0.53,5217.71,233350.10,15.74,86.06,10.61,24.54,68.65
4998,2.93,0.38,6.2,55.5,6981.70,7108.1,12.96,1.930665e+08,71399351.06,62632.5,...,0.02,1.344100e+10,0.52,3070.39,136859.84,15.01,85.64,7.60,27.38,68.70
4999,2.45,0.03,6.5,58.8,7005.98,7137.0,13.51,1.924247e+08,71760369.36,51810.0,...,0.02,1.313300e+10,0.55,4901.51,221149.20,15.10,74.14,14.66,25.70,68.63

In [6]:
schedule.to_csv('./processed/schedule.csv')

In [7]:
states.to_csv('./processed/states.csv')